

services:

  catalogdb:
    image: mongo

  basketdb:
    image: redis

  rabbitmq:
    image: rabbitmq:3-management-alpine

  
  catalog.api:
    image: koussayoune/projet:catalogapi
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basket.api:
    image: koussayoune/projet:basketapi
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=basketdb:6379"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:80"

  frontend-basket:
    image: koussayoune/projet:frontend-basket
    container_name: frontend-basket
    depends_on:
      - basket.api
    ports:
      - "8002:80"

  frontend-catalog:
    image: koussayoune/projet:frontend-catalog
    container_name: frontend-catalog
    depends_on:
      - catalog.api
    ports:
      - "8003:80"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      -  ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - pipeline_default
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

networks:
  pipeline_default:
    external: true