global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'catalogapi'
    static_configs:
      - targets: ['catalog.api:8080']

  - job_name: 'basketapi'
    static_configs:
      - targets: ['basket.api:8080']
