global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'basketapi'
    static_configs:
      - targets: ['basketapi:80']

  - job_name: 'catalogapi'
    static_configs:
      - targets: ['catalogapi:80']
